server:
  port: 8888

spring:
  application:
    name: config-server

  # read config from git
  cloud:
    config:
      server:
        bootstrap: false
        git:
          # clone-on-start: true
          uri: https://github.com/serviceeruka/cloud-config-server
